server:
  port: 8080
  
  
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - name: MyPreFilter
      - name: MyPostFilter
        

management:  endpoints:    web:      exposure:        include:        - "*"