server:
  port: 7070
  
spring:  application:    name: reactive-client
    
eureka:  client:    service-url:      defaultZone: http://localhost:8761/eureka
      
info:
  build:
    artificatId: '@project.artifact@'
    groupId: '@project.groupId@'
    version: '@project.version@'
  java:
      version: '@java.version@'
      
management:  endpoints:    web:      exposure:        include:        - "*"  endpoint:    shutdown:      enabled: true