com:
  training:
    custom:
      propName: dev-profile


spring:
  config:
    activate:
      on-profile:
      - dev
server:
  port: 8082
        
---

com:
  training:
    custom:
      propName: admin-profile

spring:
  config:
    activate:
      on-profile:
      - prod
      
server:
  port: 8085
  
        