resilience4j:
  circuitbreaker:
    instances:
      order-service:
        register-health-indicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: false
        failureRateThreshold: 50
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 20
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED



management:
  health:    circuitbreakers:      enabled: true  endpoints:    web:      exposure:        include:        - "*"  endpoint:    health:      show-details: always  